#!/usr/bin/python

from letterplay.dictionary import Dictionary
from letterplay.board import Board
from letterplay.suggestors.basic import Suggestor


dictionary = Dictionary('words')
board = Board()
board.setup('doyisndryyahbtuooqygeedrp')
suggestor = Suggestor(dictionary, board)
suggestor.prep()

import cProfile
cProfile.run('suggestor.suggestions_for(1)', 'profile-data')
